import './styles.scss';
import './scripts/headers.js';
import './scripts/footer.js';
import './scripts/add-modal.js';
import './scripts/card-gallery.js';
import './scripts/menu.js';
import './scripts/reg-modal.js';
import './scripts/add-modal-open-close';
import './scripts/searchModal.js';
// import './scripts/card-gallery.js';
import './scripts/slider.js';
